<a href="https://colab.research.google.com/github/C4-H10/Optimasi-Portofolio-Pada-Saham-IDX30-Menggunakan-Metode-Single-Index-Model-SIM-/blob/main/Optimasi_Portofolio_Single_Index_Model_(SIM)_pada_Saham_IDX30.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#KONFIGURASI

Data yang akan dianalisis merupakan data harian dengan konfigurasi sebagai berikut :

In [ ]:
Tanggal_Mulai = "2025-03-26"
Tanggal_Selesai = "2026-03-26"

LIST_SAHAM = [
    "AADI.JK", "ADRO.JK", "AMRT.JK", "ANTM.JK", "ASII.JK",
    "BBCA.JK", "BBNI.JK", "BBRI.JK", "BMRI.JK", "BRPT.JK",
    "BUMI.JK", "CPIN.JK", "EMTK.JK", "GOTO.JK", "ICBP.JK",
    "INCO.JK", "INDF.JK", "INKP.JK", "ISAT.JK", "JPFA.JK",
    "KLBF.JK", "MBMA.JK", "MDKA.JK", "MEDC.JK", "PGAS.JK",
    "PGEO.JK", "PTBA.JK", "TLKM.JK", "UNTR.JK", "UNVR.JK"
]

#List Suku Bunga BI (BI Rate)
suku_bunga_list = [0.0475,0.0475,0.0475,0.0475,0.0475,0.0475,0.0475,0.05,0.0525,0.055,0.055,0.0575]

Data BI-Rate bisa diakses melalui link berikut https://www.bi.go.id/id/statistik/indikator/BI-Rate.aspx

#IMPORT DATA

##DATA SAHAM

In [ ]:
!pip install yfinance

Requirement already satisfied: yfinance in /usr/local/lib/python3.12/dist-packages (0.2.66)
Requirement already satisfied: pandas>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from yfinance) (2.2.2)
Requirement already satisfied: numpy>=1.16.5 in /usr/local/lib/python3.12/dist-packages (from yfinance) (2.0.2)
Requirement already satisfied: requests>=2.31 in /usr/local/lib/python3.12/dist-packages (from yfinance) (2.32.4)
Requirement already satisfied: multitasking>=0.0.7 in /usr/local/lib/python3.12/dist-packages (from yfinance) (0.0.12)
Requirement already satisfied: platformdirs>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from yfinance) (4.9.4)
Requirement already satisfied: pytz>=2022.5 in /usr/local/lib/python3.12/dist-packages (from yfinance) (2025.2)
Requirement already satisfied: frozendict>=2.3.4 in /usr/local/lib/python3.12/dist-packages (from yfinance) (2.4.7)
Requirement already satisfied: peewee>=3.16.2 in /usr/local/lib/python3.12/dist-packages (from yfinance) (4.0.3)
Requirement already satisfied: beautifulsoup4>=4.11.1 in /usr/local/lib/python3.12/dist-packages (from yfinance) (4.13.5)
Requirement already satisfied: curl_cffi>=0.7 in /usr/local/lib/python3.12/dist-packages (from yfinance) (0.14.0)
Requirement already satisfied: protobuf>=3.19.0 in /usr/local/lib/python3.12/dist-packages (from yfinance) (5.29.6)
Requirement already satisfied: websockets>=13.0 in /usr/local/lib/python3.12/dist-packages (from yfinance) (15.0.1)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4>=4.11.1->yfinance) (2.8.3)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4>=4.11.1->yfinance) (4.15.0)
Requirement already satisfied: cffi>=1.12.0 in /usr/local/lib/python3.12/dist-packages (from curl_cffi>=0.7->yfinance) (2.0.0)
Requirement already satisfied: certifi>=2024.2.2 in /usr/local/lib/python3.12/dist-packages (from curl_cffi>=0.7->yfinance) (2026.2.25)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.3.0->yfinance) (2.9.0.post0)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.3.0->yfinance) (2025.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.31->yfinance) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.31->yfinance) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.31->yfinance) (2.5.0)
Requirement already satisfied: pycparser in /usr/local/lib/python3.12/dist-packages (from cffi>=1.12.0->curl_cffi>=0.7->yfinance) (3.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=1.3.0->yfinance) (1.17.0)

In [ ]:
import yfinance as yf
import pandas as pd
df = yf.download(LIST_SAHAM,
                 start=Tanggal_Mulai,
                 end=Tanggal_Selesai,
                 auto_adjust=True)['Close']

df.info()

[*********************100%***********************]  30 of 30 completed

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 231 entries, 2025-03-26 to 2026-03-25
Data columns (total 30 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   AADI.JK  231 non-null    float64
 1   ADRO.JK  231 non-null    float64
 2   AMRT.JK  231 non-null    float64
 3   ANTM.JK  231 non-null    float64
 4   ASII.JK  231 non-null    float64
 5   BBCA.JK  231 non-null    float64
 6   BBNI.JK  231 non-null    float64
 7   BBRI.JK  231 non-null    float64
 8   BMRI.JK  231 non-null    float64
 9   BRPT.JK  231 non-null    float64
 10  BUMI.JK  231 non-null    float64
 11  CPIN.JK  231 non-null    float64
 12  EMTK.JK  231 non-null    float64
 13  GOTO.JK  231 non-null    float64
 14  ICBP.JK  231 non-null    float64
 15  INCO.JK  231 non-null    float64
 16  INDF.JK  231 non-null    float64
 17  INKP.JK  231 non-null    float64
 18  ISAT.JK  231 non-null    float64
 19  JPFA.JK  231 non-null    float64
 20  KLBF.JK  231 non-null    float64
 21  MBMA.JK  231 non-null    float64
 22  MDKA.JK  231 non-null    float64
 23  MEDC.JK  231 non-null    float64
 24  PGAS.JK  231 non-null    float64
 25  PGEO.JK  231 non-null    float64
 26  PTBA.JK  231 non-null    float64
 27  TLKM.JK  231 non-null    float64
 28  UNTR.JK  231 non-null    float64
 29  UNVR.JK  231 non-null    float64
dtypes: float64(30)
memory usage: 55.9 KB

In [ ]:
df.head()

Ticker,AADI.JK,ADRO.JK,AMRT.JK,ANTM.JK,ASII.JK,BBCA.JK,BBNI.JK,BBRI.JK,BMRI.JK,BRPT.JK,...,KLBF.JK,MBMA.JK,MDKA.JK,MEDC.JK,PGAS.JK,PGEO.JK,PTBA.JK,TLKM.JK,UNTR.JK,UNVR.JK
Date,,,,,,,,,,,,,,,,,,,,,
2025-03-26,6170.670898,1568.816895,1983.831665,1571.742188,4419.838867,8113.821777,3590.144775,3643.608643,4586.586914,680.0,...,1074.451660,302.0,1450.0,989.724243,1400.278198,789.660706,2227.146729,2261.849365,21488.732422,1162.857910
2025-03-27,6123.746094,1573.079956,2023.310913,1557.453613,4530.334961,8090.027344,3581.697266,3689.153809,4631.116699,710.0,...,1108.638794,300.0,1430.0,984.919739,1404.795288,775.215698,2236.020020,2234.039795,21534.453125,1186.302490
2025-04-08,5396.404297,1402.556396,2003.571289,1333.599487,4125.183105,7399.995605,3404.302002,3315.683838,4159.099121,645.0,...,1030.496826,256.0,1220.0,932.070374,1305.420654,736.695679,2147.289062,2122.801270,18379.724609,1106.590576
2025-04-09,5396.404297,1406.819580,2043.050537,1405.042236,4254.095215,7542.761230,3412.749268,3306.574951,4194.723145,600.0,...,1079.335449,242.0,1040.0,898.439026,1346.073853,741.510681,2182.781250,2150.610840,18791.210938,1083.145752
2025-04-10,5631.030762,1449.450439,2260.186279,1552.690796,4336.967285,7828.291504,3598.592285,3461.428223,4475.261719,655.0,...,1118.406494,262.0,1220.0,975.310791,1400.278198,775.215698,2377.989502,2178.420654,19934.228516,1205.058350

In [ ]:
df.to_excel('data_idx30.xlsx', index=True)

In [ ]:
# Dataframe Return Saham (Log Return)
import numpy as np

return_saham = np.log(df / df.shift(1))
return_saham = return_saham.dropna()
return_saham.head()

Ticker,AADI.JK,ADRO.JK,AMRT.JK,ANTM.JK,ASII.JK,BBCA.JK,BBNI.JK,BBRI.JK,BMRI.JK,BRPT.JK,...,KLBF.JK,MBMA.JK,MDKA.JK,MEDC.JK,PGAS.JK,PGEO.JK,PTBA.JK,TLKM.JK,UNTR.JK,UNVR.JK
Date,,,,,,,,,,,,,,,,,,,,,
2025-03-27,-0.007634,0.002714,0.019705,-0.009132,0.024693,-0.002937,-0.002356,0.012423,0.009662,0.043172,...,0.031323,-0.006645,-0.013889,-0.004866,0.003221,-0.018462,0.003976,-0.012371,0.002125,0.019961
2025-04-08,-0.126441,-0.114739,-0.009804,-0.155171,-0.093685,-0.089153,-0.050797,-0.106733,-0.107500,-0.096015,...,-0.073092,-0.158605,-0.158824,-0.055152,-0.073366,-0.050966,-0.040491,-0.051075,-0.158406,-0.069558
2025-04-09,0.000000,0.003035,0.019513,0.052186,0.030772,0.019109,0.002478,-0.002751,0.008529,-0.072321,...,0.046304,-0.056240,-0.159630,-0.036749,0.030667,0.006515,0.016394,0.013015,0.022141,-0.021414
2025-04-10,0.042560,0.029853,0.101003,0.099922,0.019293,0.037156,0.053025,0.045768,0.064737,0.087706,...,0.035559,0.079407,0.159630,0.082097,0.039479,0.044452,0.085656,0.012848,0.059049,0.106658
2025-04-11,-0.016807,0.008785,-0.035559,0.036149,0.000000,0.006061,0.030060,0.010635,0.014815,0.015152,...,0.030110,-0.038915,0.067352,0.000000,0.019170,0.000000,0.000000,-0.008547,0.002291,0.019268

##DATA IHSG

In [ ]:
ihsg = yf.download("^JKSE",
                   start=Tanggal_Mulai,
                   end=Tanggal_Selesai,
                   auto_adjust=True)['Close']

ihsg.to_excel('ihsg.xlsx', index=True)
ihsg.head()

[*********************100%***********************]  1 of 1 completed

Ticker            ^JKSE
Date
2025-03-26  6472.355957
2025-03-27  6510.620117
2025-04-08  5996.142090
2025-04-09  5967.987793
2025-04-10  6254.023926

In [ ]:
# Dataframe Return IHSG (Log Return)
return_IHSG = np.log(ihsg / ihsg.shift(1))
return_IHSG = return_IHSG.dropna()
return_IHSG.head()

Ticker         ^JKSE
Date
2025-03-27  0.005895
2025-04-08 -0.082318
2025-04-09 -0.004706
2025-04-10  0.046815
2025-04-11  0.001311

#PERHITUNGAN BOBOT PORTOFOLIO

### **Penjelasan Variabel**

1.  **RATA RATA / E(Ri)**: Tingkat pengembalian yang diharapkan (*expected return*) dari masing-masing saham, dihitung dari rata-rata imbal hasil historis selama periode pengamatan.
2.  **VARIAN**: Risiko total saham yang mencerminkan besarnya fluktuasi imbal hasil harian terhadap nilai rata-ratanya.
3.  **BETA ($\beta$)**: Indikator risiko sistematis yang mengukur sensitivitas imbal hasil saham terhadap pergerakan pasar (IHSG).
4.  **ALFA ($\alpha$)**: Komponen imbal hasil yang bersifat independen atau tidak dipengaruhi oleh pergerakan pasar secara keseluruhan.
5.  **VAR RESIDUAL ($\sigma_{ei}^2$)**: Risiko unik perusahaan (risiko tidak sistematis) yang dapat diminimalisir melalui diversifikasi.
6.  **ERB (Excess Return to Beta)**: Rasio kelebihan imbal hasil di atas suku bunga bebas risiko per unit risiko sistematis. Digunakan sebagai dasar utama pemeringkatan saham.
7.  **Ai & Bi**: Variabel antara yang mengintegrasikan nilai *excess return*, beta, dan risiko residual untuk menentukan titik pembatas.
8.  **Ci (Cut-off Point)**: Nilai batas akumulatif. Saham yang terpilih masuk portofolio optimal adalah saham yang memiliki nilai **ERB > Ci**.
9.  **Zi**: Koefisien bantuan untuk menentukan proporsi dana, yang mempertimbangkan selisih ERB terhadap nilai *cut-off* ($C^*$) dan risiko residual.
10. **Bobot (Wi)**: Proporsi alokasi modal (persentase dana) yang diinvestasikan pada masing-masing saham dalam portofolio sehingga total bobot adalah 100%.

In [ ]:
market_return = return_IHSG.iloc[:, 0]
var_market_sample = market_return.var(ddof=1)
var_market_pop = market_return.var(ddof=0)

rata_rata_suku_bunga = np.mean(suku_bunga_list)
rf = rata_rata_suku_bunga / len(return_saham)
print(f"Rata-rata harian suku bunga BI : {rf}")

betas = {}
for col in return_saham.columns:
    cov_p = np.cov(return_saham[col], market_return, ddof=0)[0][1]
    betas[col] = cov_p / var_market_sample

beta_series = pd.Series(betas)
rata_rata = return_saham.mean()
varian_saham = return_saham.var(ddof=0)
varian_residual = varian_saham - (beta_series**2 * var_market_pop)

ai = (rata_rata - (((rata_rata - rf) / beta_series))) / varian_residual
bi = (beta_series**2) / varian_residual

summary_df = pd.DataFrame({
    'RATA RATA': rata_rata,
    'VARIAN': varian_saham,
    'SUM': return_saham.sum(),
    'BETA': beta_series,
    'ALFA': rata_rata - (beta_series * market_return.mean()),
    'E(Ri)': rata_rata,
    'ERB': (rata_rata - rf) / beta_series,
    'VAR RESIDUAL': varian_residual,
    'Ai': ai,
    'Bi': bi
})

summary_df.index.name = 'Saham'
summary_df = summary_df.sort_values(by='ERB', ascending=False) #sort berdasarkan ERB
summary_df['Ai Kumulatif'] = summary_df['Ai'].cumsum()
summary_df['Bi Kumulatif'] = summary_df['Bi'].cumsum()
summary_df['Ci'] = (var_market_pop * summary_df['Ai Kumulatif']) / (1 + (var_market_pop * summary_df['Bi Kumulatif']))
summary_df['ERB - Ci'] = summary_df['ERB'] - summary_df['Ci']
summary_df['Zi'] = (summary_df['BETA']/summary_df['VAR RESIDUAL'])*summary_df['ERB - Ci']
summary_df = summary_df[summary_df['ERB - Ci'] > 0]
summary_df['Bobot (Wi)'] = summary_df['Zi']/summary_df['Zi'].sum()
summary_df

Rata-rata harian suku bunga BI : 0.00021829710144927536

,RATA RATA,VARIAN,SUM,BETA,ALFA,E(Ri),ERB,VAR RESIDUAL,Ai,Bi,Ai Kumulatif,Bi Kumulatif,Ci,ERB - Ci,Zi,Bobot (Wi)
Saham,,,,,,,,,,,,,,,,
AADI.JK,0.002582,0.000723,0.593872,0.476670,0.002332,0.002582,0.004959,0.000682,-3.483497,333.006424,-3.483497,333.006424,-0.000589,0.005548,3.876083,0.059684
MEDC.JK,0.002478,0.000829,0.569945,0.592156,0.002167,0.002478,0.003816,0.000766,-1.746775,457.751984,-5.230272,790.758407,-0.000821,0.004637,3.584848,0.055200
ANTM.JK,0.003627,0.001385,0.834289,1.021817,0.003091,0.003627,0.003336,0.001198,0.242924,871.362531,-4.987348,1662.120939,-0.000689,0.004025,3.432506,0.052854
INCO.JK,0.004011,0.001546,0.922539,1.426415,0.003263,0.004011,0.002659,0.001181,1.145025,1723.041499,-3.842323,3385.162438,-0.000429,0.003088,3.729732,0.057431
PTBA.JK,0.001521,0.000263,0.349851,0.532354,0.001242,0.001521,0.002447,0.000212,-4.368620,1336.809982,-8.210943,4721.972420,-0.000797,0.003244,8.147272,0.125453
UNVR.JK,0.002214,0.001101,0.509227,0.824551,0.001782,0.002214,0.002420,0.000979,-0.210825,694.610296,-8.421768,5416.582716,-0.000766,0.003186,2.684278,0.041333
ADRO.JK,0.002246,0.000731,0.516662,0.840660,0.001805,0.002246,0.002412,0.000604,-0.275034,1170.152744,-8.696802,6586.735459,-0.000715,0.003127,4.353206,0.067031
MDKA.JK,0.003428,0.001951,0.788457,1.432394,0.002677,0.003428,0.002241,0.001583,0.749755,1295.718772,-7.947047,7882.454231,-0.000590,0.002831,2.561127,0.039437
MBMA.JK,0.003837,0.002633,0.882618,1.729578,0.002930,0.003837,0.002093,0.002096,0.832344,1426.921594,-7.114703,9309.375825,-0.000478,0.002570,2.120644,0.032654
PGAS.JK,0.001451,0.000460,0.333719,0.591503,0.001141,0.001451,0.002084,0.000397,-1.593122,880.581906,-8.707825,10189.957731,-0.000552,0.002636,3.924579,0.060431
BUMI.JK,0.004003,0.002829,0.920725,1.855332,0.003030,0.004003,0.002040,0.002211,0.887783,1556.658271,-7.820042,11746.616002,-0.000451,0.002491,2.090324,0.032187
INKP.JK,0.003051,0.001200,0.701768,1.389240,0.002323,0.003051,0.002039,0.000854,1.184699,2259.307674,-6.635343,14005.923676,-0.000339,0.002378,3.867281,0.059549
ASII.JK,0.001743,0.000567,0.400966,0.820530,0.001313,0.001743,0.001859,0.000446,-0.258384,1509.222173,-6.893727,15515.145849,-0.000327,0.002185,4.019724,0.061896
UNTR.JK,0.001562,0.000632,0.359174,0.867549,0.001107,0.001562,0.001548,0.000497,0.026587,1515.017173,-6.867140,17030.163022,-0.000304,0.001852,3.234484,0.049805
BRPT.JK,0.003155,0.002101,0.725700,1.958236,0.002128,0.003155,0.001500,0.001413,1.171273,2713.159301,-5.695867,19743.322323,-0.000225,0.001725,2.389631,0.036796
TLKM.JK,0.001642,0.000617,0.377740,0.987585,0.001124,0.001642,0.001442,0.000442,0.453510,2207.231886,-5.242357,21950.554210,-0.000190,0.001632,3.648356,0.056178
ISAT.JK,0.001813,0.001113,0.417071,1.219449,0.001174,0.001813,0.001308,0.000846,0.597247,1757.514424,-4.645110,23708.068633,-0.000159,0.001467,2.113756,0.032548
EMTK.JK,0.002243,0.002237,0.515861,1.713849,0.001344,0.002243,0.001181,0.001711,0.620514,1716.913112,-4.024596,25424.981745,-0.000130,0.001311,1.313463,0.020225
JPFA.JK,0.000749,0.000976,0.172212,0.679545,0.000392,0.000749,0.000781,0.000893,-0.035664,517.105997,-4.060260,25942.087742,-0.000129,0.000909,0.692027,0.010656
PGEO.JK,0.001005,0.001099,0.231139,1.085373,0.000436,0.001005,0.000725,0.000888,0.315507,1326.598478,-3.744753,27268.686220,-0.000114,0.000839,1.025211,0.015786
BBNI.JK,0.000513,0.000346,0.118052,0.659306,0.000167,0.000513,0.000447,0.000268,0.245567,1620.508659,-3.499186,28889.194879,-0.000102,0.000549,1.349200,0.020775
BMRI.JK,0.000349,0.000426,0.080284,0.982540,-0.000166,0.000349,0.000133,0.000253,0.853617,3815.602101,-2.645569,32704.796980,-0.000069,0.000202,0.785199,0.012091

In [ ]:
print(f"Jumlah saham yang terpilih sebanyak : {len(summary_df)} saham")
print(summary_df[["Bobot (Wi)"]].sort_values(by="Bobot (Wi)", ascending=False))

Jumlah saham yang terpilih sebanyak : 22 saham
         Bobot (Wi)
Saham
PTBA.JK    0.125453
ADRO.JK    0.067031
ASII.JK    0.061896
PGAS.JK    0.060431
AADI.JK    0.059684
INKP.JK    0.059549
INCO.JK    0.057431
TLKM.JK    0.056178
MEDC.JK    0.055200
ANTM.JK    0.052854
UNTR.JK    0.049805
UNVR.JK    0.041333
MDKA.JK    0.039437
BRPT.JK    0.036796
MBMA.JK    0.032654
ISAT.JK    0.032548
BUMI.JK    0.032187
BBNI.JK    0.020775
EMTK.JK    0.020225
PGEO.JK    0.015786
BMRI.JK    0.012091
JPFA.JK    0.010656

#KINERJA PORTOFOLIO (INDEKS TREYNOR)

**Ekspektasi Return Portofolio** : <br>
rata-rata tingkat keuntungan yang diharapkan setiap hari
<br><br>
**Beta Portofolio** : <br>
Jika beta > 1 portofolio lebih volatil dibandingkan pasar.<br>
Jika beta < 1 portofolio lebih stabil. <br>
Jika beta = 1 maka portofolio bergerak mengikuti pergerakan pasar (IHSG).
<br><br>
**Indeks Treynor** :<br>
Jika Indeks Treynor portofolio > Indeks Treynor IHSG, maka portofolio yang disusun sudah optimal

In [ ]:
# Rata-rata Return IHSG
rata_rata_ihsg = return_IHSG.mean().iloc[0]

# Suku Bunga Bebas Risiko (Rf)
risk_free = rf

# Beta IHSG
beta_market = 1.0

# Rumus Treynor IHSG
treynor_ihsg = (rata_rata_ihsg - risk_free) / beta_market

# Ekspektasi Return Portofolio
return_portofolio = (summary_df['Bobot (Wi)'] * summary_df['E(Ri)']).sum()

# Beta Portofolio
beta_portofolio = (summary_df['Bobot (Wi)'] * summary_df['BETA']).sum()

# Rumus Treynor Portofolio
treynor_portofolio = (return_portofolio - risk_free) / beta_portofolio

print("=== KINERJA PORTOFOLIO (INDEKS TREYNOR) ===")
print(f"Return Harian IHSG         : {rata_rata_ihsg:.6f}")
print(f"Return Harian Portofolio   : {return_portofolio:.6f}")
print("-" * 45)
print(f"Beta Portofolio            : {beta_portofolio:.6f}")
print("-" * 45)
print(f"Indeks Treynor IHSG        : {treynor_ihsg:.6f}")
print(f"Indeks Treynor Portofolio  : {treynor_portofolio:.6f}")
print("-" * 45)

if treynor_portofolio > treynor_ihsg:
    print("KESIMPULAN: Portofolio OPTIMAL")
else:
    print("KESIMPULAN: Portofolio BELUM OPTIMAL")

=== KINERJA PORTOFOLIO (INDEKS TREYNOR) ===
Return Harian IHSG         : 0.000524
Return Harian Portofolio   : 0.002342
---------------------------------------------
Beta Portofolio            : 0.991275
---------------------------------------------
Indeks Treynor IHSG        : 0.000306
Indeks Treynor Portofolio  : 0.002142
---------------------------------------------
KESIMPULAN: Portofolio OPTIMAL